language: elixir
elixir:
  - 1.4.5
  - 1.5.1
otp_release:
  - 19.3
  - 20.0
sudo: false
install:
  - mix do local.hex --force, local.rebar --force
  - MIX_ENV=test mix deps.get # need to explicitly get test deps, see mix.exs
  - MIX_ENV=test mix do compile
script: MIX_ENV=test mix do coveralls.travis, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ef67a7e3-b7fa-45b8-acd4-99f3ccaa2d3a
