language: elixir
elixir:
  - 1.6.1
  - 1.7.2
sudo: false
install:
  - mix do local.hex --force, local.rebar --force
  - MIX_ENV=test mix do deps.get, compile # need to explicitly get test deps, see mix.exs
script: MIX_ENV=test mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ef67a7e3-b7fa-45b8-acd4-99f3ccaa2d3a
